package com.mycompany.playlist;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
public class Interfaz1 extends javax.swing.JFrame {
    private JButton playSongsButton;
    private JButton createPlaylistButton;
    private JButton salirDelProgramaButton;
    public Interfaz1() {
        setTitle("Reproductor de música");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        playSongsButton = new JButton("Reproducir canciones");
        createPlaylistButton = new JButton("Crear lista de reproducción");
        salirDelProgramaButton = new JButton("Salir del programa");
        //Añadir los botones al panel
        JPanel panel = new JPanel();
        panel.add(playSongsButton);
        panel.add(createPlaylistButton);
        panel.add(salirDelProgramaButton);
        //Añadir el panel a la ventana
        getContentPane().add(panel);
        //Añadir los action listeners a los botones
        playSongsButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Código para reproducir canciones
            }
        });
        createPlaylistButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Código para crear una lista de reproducción
            }
        });
        salirDelProgramaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Código para salir del programa
                System.exit(0);
            }});
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        Interfaz1 interfaz = new Interfaz1();
        interfaz.setVisible(true);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

